### PR TITLE
Completed HTML file and added image folder

### LINKED ISSUE #1: HTML - semantic markup with containers

### PR DESCRIPTION
**Pull request by casserole27**
I initialized the repository, copied the scrim code, and created two issues within Github. We can create more issues once we start looking at the JS logic.

I have completed the initial HTML file. I wasn't sure what image we should use, so I made a fun little Din Grogu image and it doesn't matter to me if it's changed. :) I tried to add IDs and comments where I feel the JS is going to happen, and hardcoded those values for now so they can be styled.  I also added a lot of divs for flexbox purposes, but they can be removed if they aren't needed.

For the CSS, I have a section in my boilerplate file that contains variables that I use frequently and also a reset. Totally fine if you don't want to use it, but I left it for now if you find it helpful.

Let me know your ideas if you think anything should be different, I'm always open to suggestions for best practices, cleaner code, new ideas etc.

### CODE REVIEW

**Review by GabrielJDavila — COMMENTED** [review]
HTML file looks great, nice job on the comments throughout the file for readability. I think it's for merging.

**Comment by casserole27** [comment]
@GabrielJDavila I had a thought. Semantically, do you think all those fields should be input fields with labels?

**Comment by GabrielJDavila** [comment]
I don't think input fields are necessary, aren't inputs normally only needed when a user enters information? I think divs might be easier to style as well. Since the information is being rendered via JS I think it's fine.

**Comment by casserole27** [comment]
> I don't think input fields are necessary, aren't inputs normally only needed when a user enters information? I think divs might be easier to style as well. Since the information is being rendered via JS I think it's fine.

I think you are right. I seem to remember a project where I was encouraged to use inputs in this way, but it does seem awkward.  I will leave the file alone. :)

**Comment by GabrielJDavila** [comment]
Also I will get to the CSS today, it's been a busy week!

**Pull request merged**
